<?php

use Illuminate\Database\Seeder;

class RecordsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('records')->insert(
            [
                ['study_date' => '2022-6-21',
                'study_time' => 2,
                'language_id' => 1,
                'content_id' => 1,
                ],
                ['study_date' => '2022-6-21',
                'study_time' => 3,
                'language_id' => 2,
                'content_id' => 1,
                ],
                ['study_date' => '2022-6-21',
                'study_time' => 4,
                'language_id' => 3,
                'content_id' => 1,
                ],
                ['study_date' => '2022-6-21',
                'study_time' => 2,
                'language_id' => 4,
                'content_id' => 1,
                ],
                ['study_date' => '2022-6-21',
                'study_time' => 0,
                'language_id' => 1,
                'content_id' => 2,
                ],
                ['study_date' => '2022-6-22',
                'study_time' => 4,
                'language_id' => 2,
                'content_id' => 2,
                ],
                ['study_date' => '2022-6-22',
                'study_time' => 2,
                'language_id' => 3,
                'content_id' => 2,
                ],
                ['study_date' => '2022-6-22',
                'study_time' => 3,
                'language_id' => 4,
                'content_id' => 2,
                ],
                ['study_date' => '2022-6-22',
                'study_time' => 3,
                'language_id' => 1,
                'content_id' => 3,
                ],
                ['study_date' => '2022-6-23',
                'study_time' => 3,
                'language_id' => 2,
                'content_id' => 3,
                ],
                ['study_date' => '2022-6-23',
                'study_time' => 2,
                'language_id' => 3,
                'content_id' => 3,
                ],
                ['study_date' => '2022-6-23',
                'study_time' => 3,
                'language_id' => 4,
                'content_id' => 3,
                ],
                ['study_date' => '2022-6-23',
                'study_time' => 4,
                'language_id' => 1,
                'content_id' => 1,
                ],
                ['study_date' => '2022-6-23',
                'study_time' => 3,
                'language_id' => 2,
                'content_id' => 1,
                ],
                ['study_date' => '2022-6-23',
                'study_time' => 2,
                'language_id' => 3,
                'content_id' => 2,
                ],
                ['study_date' => '2022-6-23',
                'study_time' => 3,
                'language_id' => 4,
                'content_id' => 2,
                ],
                ['study_date' => '2022-6-24',
                'study_time' => 4,
                'language_id' => 1,
                'content_id' => 3,
                ],
                ['study_date' => '2022-6-24',
                'study_time' => 3,
                'language_id' => 2,
                'content_id' => 3,
                ],
                ['study_date' => '2022-6-24',
                'study_time' => 2,
                'language_id' => 3,
                'content_id' => 3,
                ],
            ]    
            );
    }
}
